# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Project.py
# Created on: 2018-10-08 15:53:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

import arcpy,os

mydir = r'Y:\\SurveyDepartment_TNTexports_TGO\\'
output = 'D:\\Temp1\\'
# listing all files in subdirectoires
def list_files(dir): 
    r = [] 
    subdirs = [x[0] for x in os.walk(dir)]
    for subdir in subdirs: 
        files = os.walk(subdir).next()[2] 
        if (len(files) > 0): 
            for file in files:
                if file.endswith(".shp"):
                    r.append(subdir+ '\\' + file)
    return r

myfiles =list_files(mydir)
"step 1 complete"

for infile in myfiles:
    outfile = infile.replace(mydir,output)
    arcpy.Project_management(infile, outfile, "GEOGCS['GCS_MMR_2000',DATUM['D_MM_2000',SPHEROID['MM_2000',6377276.345,300.8017]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]", "'GCS_WGS_1984_to_Myanmar2000 + WGS_to_MMR2000'", "PROJCS['Universal Transverse Mercator - 47 (E 96 to E 102)',GEOGCS['Myanmar2000',DATUM['Myanmar Datum 2000 3par',SPHEROID['Everest 1830',6377276.3452,300.8017]],PRIMEM['Greenwich',0.0],UNIT['Decimal_Degree',0.0174532924199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',99.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")
    print(infile+"successfully complete")

'''
for x in myfiles:
    print(x)
    print(x.replace(mydir,output))
    '''
    